apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260622-135113-x8nayy3xjt6j-service
spec:
  selector:
    app: enterprise-system-20260622-135113-x8nayy3xjt6j
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
